--- 
title: "Covid-Crime-Relationship-Analysis"
author: "Victoria Meng & Jessie Yu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Our project is to focus on how COVID-19 has been progressing in NYC, and how the arrival of COVID changed the crime events in NYC. The motivation behind this is mainly to provide for people on the government side, who are trying to figure out where to prioritize resources if COVID is more severely spreading, and our analysis can also be utilized as a study case for similar pandemic or events like COVID that might happen again in the far far future, specially to assist the government officials to allocate resources in the aspect of crimes. Nonetheless, this project is for the general public audience as well, to those who are curious about COVID exposure and COVID vaccinations, as well as its relation with crime data in NYC. 


This project have detailed examination towards the spreading of COVID in NYC across time. We also explored the possible correlation between Hate crimes and Shooting incidence in NYC with COVID cases through out the years by each boroughs. 